backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
site_url: "https://example.com"
media_folder: "src/images"
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/njk.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Post Feed Heading", name: "postsHeading", widget: "string", default: "Latest posts"}
          - {label: "Archive Link Text", name: "archiveButtonText", widget: "string", default: "See all posts"}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
#  - name: "generic_pages"
#    label: "Generic Pages"
#    folder: "src/pages"
#    slug: "{{slug}}"
#    preview_path: "pages/{{slug}}"
#    create: true
#    fields:
#      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Permalink Override (Pattern: '/your-slug/index.html')", name: "permalink", widget: "string", required: false}
#      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
#      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
#      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
#      - {label: "Body", name: "body", widget: "markdown"}