backend:
  name: git-gateway
  branch: master
site_url: "https://example.com"
media_folder: "src/images"
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Intro (boven logo)", name: "intro", widget: "string"}
          - {label: "Uitleg (onder logo)", name: "body", widget: "text"}
          - {label: "Waar", name: "waar", widget: "string"}
          - {label: "Wanneer", name: "wanneer", widget: "string"}
          - {label: "Aanmelden", name: "aanmelden", widget: "markdown"}
          - {label: "Organisatie", name: "organisatie", widget: "text"}
          - {label: "Achtergrond", name: "achtergrond", widget: "text"}

#  - name: "generic_pages"
#    label: "Generic Pages"
#    folder: "src/pages"
#    slug: "{{slug}}"
#    preview_path: "pages/{{slug}}"
#    create: true
#    fields:
#      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Permalink Override (Pattern: '/your-slug/index.html')", name: "permalink", widget: "string", required: false}
#      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
#      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
#      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
#      - {label: "Body", name: "body", widget: "markdown"}